variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: homestead
  MYSQL_PASSWORD: secret
  MYSQL_DATABASE: homestead
  DB_HOST: mysql
  DB_USERNAME: homestead
  DB_PASSWORD: secret
  DB_DATABASE: homestead
  DB_CONNECTION: mysql
  DB_PORT: 3306

cache:
  paths:
    - vendor/
    - node_modules/
    - public/

stages:
  - test
  - deploy

.config:
  image: lorisleiva/laravel-docker:8.2
  services:
    - name: mysql:8.0
      alias: mysql
      variables:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: homestead
        MYSQL_USER: homestead
        MYSQL_PASSWORD: secret
  before_script:
    # Install Node dependencies.
    - npm install
    # install composer dependencies
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
    # Copy over example configuration.
    - cp .env.example .env
    # Update database configuration
    - sed -i "s/DB_HOST=.*/DB_HOST=mysql/" .env
    - sed -i "s/DB_USERNAME=.*/DB_USERNAME=homestead/" .env
    - sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=secret/" .env
    - sed -i "s/DB_DATABASE=.*/DB_DATABASE=homestead/" .env
    # Wait for MySQL to be ready
    - |
      until mysql -h mysql -u homestead -psecret -e "SELECT 1"; do
        echo "Waiting for MySQL to be ready..."
        sleep 1
      done
    # Generate an application key. Re-cache.
    - php artisan key:generate
    - php artisan config:cache
    # Run database migrations.
    - php artisan migrate:refresh --seed
    # Run database seed
    - php artisan db:seed

check:
  stage: test
  extends:
    - .config
  script:
    # run laravel tests
    - php vendor/bin/phpunit --coverage-text --colors=never
    # run frontend tests
    # if you have any task for testing frontend
    # set it in your package.json script
    # comment this out if you don't have a frontend test
    #- npm test

deploy:
  stage: deploy
  extends:
    - .config
  script: echo "Define your deployment script!"
  environment: production

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml