stages:
  - sast

sast:
  stage: sast
  image: php:8.2
  before_script:
    - apt-get update && apt-get install -y git unzip
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install
  script:
    - vendor/bin/phpcs --standard=PSR2 src/
    - vendor/bin/phpstan analyse src/
  artifacts:
    paths:
      - gl-sast-report.json
  allow_failure: false
  only:
    - main