name: CI

on:
  - pull_request
  - push

jobs:
  tests:
      name: Tests

      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0

        - name: Setup PHP with Xdebug
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.2'
            coverage: xdebug

        - name: Install dependencies with composer
          run: composer update --no-ansi --no-interaction --no-progress

        - name: Prepare SQLite database
          run: |
            touch database/database.sqlite

        - name: Copy .env.example to .env and set SQLite
          run: |
            cp .env.example .env
            sed -i 's/^DB_CONNECTION=.*/DB_CONNECTION=sqlite/' .env
            sed -i 's/^DB_DATABASE=.*/DB_DATABASE=database\/database.sqlite/' .env
            sed -i 's/^DB_HOST=.*/DB_HOST=/' .env
            sed -i 's/^DB_USERNAME=.*/DB_USERNAME=/' .env
            sed -i 's/^DB_PASSWORD=.*/DB_PASSWORD=/' .env

        - name: Install dependencies with composer (prod)
          run: composer install --no-ansi --no-interaction --no-progress

        - name: Run migrations
          run: php artisan migrate --force

        - name: Run tests with phpunit/phpunit
          run: vendor/bin/pest --coverage-clover=coverage.xml

        - name: SonarQube Scan
          uses: SonarSource/sonarqube-scan-action@v4
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
